useUserInfo composables の修正
shion1305/ynufes-mypage-frontend pull request #51
Opened 2024-02-27 00:16 UTC by tomoyahiroe

# PRで実装される機能

# PRで修正される機能
- #48 の修正で useApiClient.post() の返り値がエラーを含むオブジェクトに変更されたので、それに適用するように useUserInfo を修正しました。

# レビューをお願いしたいポイント

2024-02-27 05:56 UTC, shion1305 commented
@tomoyahiroe 一旦rebaseお願いします🙏

2024-02-29 13:08 UTC, tomoyahiroe commented
コンフリクト解消したので確認よろです🙏🏻

2024-02-29 13:38 UTC, shion1305 requested changes
ありがとうございます! 一部変更提案したので確認お願いします～
スキーは楽しいかい？

2024-02-29 13:38 UTC, shion1305 commented on composables/useUserInfo.ts
> +    return !resp.error
```suggestion
      return false
    }
    return true
```

```suggestion
    }
    return !resp.error
```
どちらかにしてみましょう!!

2024-03-11 05:25 UTC, closed without merging