issue #55 fix welcome page style
shion1305/ynufes-mypage-frontend pull request #56
Opened 2024-03-12 04:21 UTC by tomoyahiroe

# PRで実装される機能
- PageTitleコンポーネントの作成
- google fontの追加
- フォント周りのユーティリティクラスの追加

# PRで修正される機能
- welcomeページの細かいデザインの修正

# レビューをお願いしたいポイント

2024-03-12 04:39 UTC, shion1305 requested changes
Google Fonts入ってなかったってびっくり,,,
プレビューしていないけれどひとまず

2024-03-12 04:39 UTC, shion1305 commented on components/PageTitle.vue
> +      v-if="!props.backLink"
```suggestion
      v-else
```

2024-03-12 04:39 UTC, shion1305 commented on pages/index.vue
> -// const greetings = ['こんにちは!', 'Hello!', 'やっほ〜', 'よくぞ参った！']
遺跡すぎて笑う

2024-03-12 04:39 UTC, shion1305 commented on pages/index.vue
> +    <PageTitle pageTitle="トップページ" backLink="/welcome" />
`/welcome` って新規登録画面じゃね?

2024-03-12 04:44 UTC, tomoyahiroe commented
修正しました!

2024-03-13 05:09 UTC, shion1305 approved these changes
遅くなりました！！！ LGTM!!

2024-03-13 05:10 UTC, merged