useOrgの作成(getAccesibleOrgs, getOrgInfo)
shion1305/ynufes-mypage-frontend pull request #66
Opened 2024-03-20 13:22 UTC by tomoyahiroe

- **:sparkles: feat: useOrg composables**
- **:sparkles: useOrgsの使用**

# PRで実装される機能

# PRで修正される機能

# レビューをお願いしたいポイント

2024-03-27 18:59 UTC, shion1305 requested changes
レビュー超超遅くなってごめん!! 確認お願いします～

2024-03-27 18:59 UTC, Shion1305 commented on pages/index.vue
> +    ? await useOrg().getOrgInfo(accessibleOrgs[0].id)
アクセスできる団体が存在しない場合にエラーとなってしまいます

2024-03-27 18:59 UTC, Shion1305 commented on composables/useOrg.ts
> +      .get('/api/v1/orgs', { org_id: orgId })
Org情報の取得は、 `api/v1/org` です
![image](https://github.com/shion1305/ynufes-mypage-frontend/assets/20254962/9f343d31-9784-494f-83a9-756ada8ccbcb)

2024-03-27 18:59 UTC, shion1305 commented on composables/useOrg.ts
> +        return resp.data as { orgs: OrgInfo }
返ってくる情報は単体なので `orgs` -> `org` の方が的確。
あとこの関数自体は `{ orgs: OrgInfo }` を返す必要はなく、ここは `OrgInfo` をダイレクトに返した方がよさそう

2024-03-27 18:59 UTC, Shion1305 commented on composables/useOrg.ts
> +      fetchedOrgInfo && fetchedOrgInfo.orgs ? fetchedOrgInfo.orgs : null
```suggestion
    orgInfo.value = fetchedOrgInfo
```
この三項演算子の処理も前に内包させた方がよさげ
以下の形になるようにする

2024-03-27 18:59 UTC, shion1305 commented on composables/useOrg.ts
> +    if (orgInfo.value) {
関数の仕様として `orgId` を引数としているので、キャッシングを利用する場合はキャッシングしている `orgID` が同じかも確認した方が良さげ。
```suggestion
    if (orgInfo.value && orgInfo.value.org_id === orgId) {
```

2024-03-27 19:01 UTC, shion1305 commented
@tomoyahiroe 

> 企画団体のSwitchに関してはノータッチです。別PRに分けることにしました。

ごめん、これ見てなかったんだけれど、今回のレビューでswitchingに該当する部分はキャッシングに該当する部分で大きな変更を必要としないと思うので、このPRで修正しちゃったほうがよさげかなと思った!

2024-03-30 02:51 UTC, shion1305 requested changes
確認お願いします～～

2024-03-30 02:51 UTC, shion1305 commented on stores/orgId.ts
> +      sessionStorage.setItem('orgId', newOrgId)
orgIdの保存場所、localstorageでもいいんじゃない?

2024-03-30 02:51 UTC, shion1305 commented on stores/orgId.ts
> +    orgId: ''
現状、 `sessionStorage` に保存しているけど、取得する部分がないので、キャッシングできていない状態。
stateで初期化する際に取得することが必要そう

2024-03-30 02:51 UTC, shion1305 commented on pages/index.vue
> -.main-content-wrapper {
`main-content-wrapper` に対する参照が残っていそうだけれど大丈夫?

2024-03-30 02:51 UTC, shion1305 commented on composables/useOrg.ts
> +    if (accessibleOrgs.value[0].id) {
`accessibleOrgs` が空配列の時に怒られそう

2024-03-30 02:52 UTC, shion1305 requested changes
追加で1件!

2024-03-30 02:52 UTC, shion1305 commented on pages/index.vue
> +    <div v-if="!accessibleOrgs">
空配列は falsy ではないので、常にtrueとなる状態になってます

2024-03-31 01:50 UTC, tomoyahiroe commented on pages/index.vue
> +    <div v-if="!accessibleOrgs">
まじか…直します！

2024-03-31 19:18 UTC, tomoyahiroe commented on pages/index.vue
> -.main-content-wrapper {
リポジトリ内検索したけど、見つからなかったよ
問題ないはず...

2024-03-31 19:18 UTC, tomoyahiroe commented on composables/useOrg.ts
> +    if (accessibleOrgs.value[0].id) {
空配列じゃないことを確かめる条件に変えるわ。

2024-03-31 22:06 UTC, shion1305 requested changes
あと1点だけお願い 🙏 
いろいろ修正ありがとうございます 🙇‍♂️

2024-03-31 22:06 UTC, shion1305 commented on pages/index.vue
> +  <main class="main-content-wrapper">
参照残っている件、こちらです!

2024-04-03 17:40 UTC, tomoyahiroe commented on pages/index.vue
> +  <main class="main-content-wrapper">
クラス名別につけてても問題ないかなって思っちゃてたわ🙏🏻
確かに使ってないし、消します〜

2024-04-03 17:59 UTC, shion1305 approved these changes
LGTM!!!

2024-04-03 18:01 UTC, merged